extends:
  - next/core-web-vitals
  - standard-with-typescript
  - prettier
plugins:
  - node
parserOptions:
  project: ./tsconfig.json
rules:
  no-new: off
  '@typescript-eslint/strict-boolean-expressions': off
  '@typescript-eslint/prefer-nullish-coalescing': off
  '@typescript-eslint/explicit-function-return-type': off
  '@typescript-eslint/restrict-template-expressions': off
  '@typescript-eslint/triple-slash-reference': off
  '@typescript-eslint/consistent-type-definitions':
    - error
    - type
  '@typescript-eslint/ban-types':
    - error
    - types:
        '{}': false
      extendDefaults: true
  import/order:
    - error
    - alphabetize:
        order: asc
        caseInsensitive: false
        orderImportKind: asc
  no-console:
    - error
    - allow:
        - info
        - error
        - warn
  no-irregular-whitespace:
    - error
    - skipTemplates: true
      skipStrings: true
  node/no-process-env: error
