extends:
  - stylelint-config-standard-scss
  - stylelint-config-prettier-scss
rules:
  selector-class-pattern:
    - '^[a-z][a-zA-Z0-9]+$'
    - message: 'Expected "%s" to be camelCase'
  scss/dollar-variable-pattern:
    - '^[a-z-]+$'
    - message: 'Expected $ variable name to be kebab-case'
  selector-pseudo-element-colon-notation: 'single'
  scss/dollar-variable-empty-line-before: null
  block-no-empty: null
  declaration-empty-line-before: null
